<?php //006f1
// This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Modul-Connector @version 6.0.1.0 PHPcust (03.08.2021) @author  Daniel Seifert support@shopmodule.com @copyright (C) 2021, D3 Data Development @see http://www.shopmodule.com
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cPwnJXmZGktilhUSIAoiGplTlqd1+bkEj98YuGv+Ji5Ym9qWGDuyf9gXlK/FnFt1rxL4HiGUq
w5Jfd260JCA/gvMsi4o1Cm2QDxUL0m1FNh67PUiqi3RtpowtY+hnRT9ZwxPLr8DALmFsNU0a7L81
1mSQc8HHAr8gnNnLDQEtZ8zOnrYT0QQ2WNzH5/IghDjRoRtOAh6KMjZ7B/wEZmRprFMHQ7tSkjZE
DldTAtdZcVk33CjuxApjmPiYXXSQNIMX2Zzo+HROsVziBuQEjUKEZNISdW9hpj72jNm0YFHWvyJG
yx5Nt2753DhH2pwycN9kWGeYCZeAmo9QtVFTHLT/J1VOSJ+v8DIh/eWHfvw2fM8IZawBahJANvPL
0WTOCGJ1hjgq8ZUwAdarAQnjJcCw+qS3sR0j0q2ds1Yv96DkHH6myJTpYOFzgz8jHIKnMw/UblvI
JEhsGT/OtzPq7eXrxmQacb1KkHW1fsKWGVfv7YuYxHOj0eFYAXH75RVAAPidr+FYE0tTm+w/Hf/O
/5om//GzoZQe7+yP1sTWDhf+7Z0CjNxtLbKZHVpzhYg47tgibahhmqk/DDA0/qFMVit+Hg+qhMfJ
lm==