<?php

/**
 * This Software is the property of Data Development and is protected
 * by copyright law - it is NOT Freeware.
 *
 * Any unauthorized use of this software without a valid license
 * is a violation of the license agreement and will be prosecuted by
 * civil and criminal law.
 *
 * https://www.d3data.de
 *
 * @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
 * @author    D3 Data Development - Daniel Seifert <support@shopmodule.com>
 * @link      http://www.oxidmodule.com
 */

$sLangName = "English";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(

//Navigation
    'charset'                              => 'UTF-8',
    'd3mxd3cleartmp'                       => 'clear TMP',
    'd3mxd3cleartmp2'                      => '<i class="fas fa-trash"></i> clear TMP',
    'd3mxd3cleartmp2_desc1'                => 'clear tmp folder now',
    'd3mxd3cleartmp2_desc2'                 => 'open clear tmp tool in new tab',
    'd3tbclclr_main'                       => 'clear TMP',
    'd3tbclclr_mtn'                        => 'maintenance',
    'd3navclrtmp_typeall'                  => 'all caches',
    'd3navclrtmp_typetpllang'              => 'tpl+language caches',
    'd3navclrtmp_typetpl'                  => 'tpl caches',
    'd3navclrtmp_typelang'                 => 'language caches',
    'd3navclrtmp_clear'                    => 'clear',

    'D3TPLBLOCKS_NOBLOCKS'                 => 'The functions are not available because no template blocks are defined.',
    'D3TPLBLOCKS_MODULE'                   => 'for this module ...',
    'D3TPLBLOCKS_CHOOSEMODULE'             => 'please select module',
    'D3TPLBLOCKS_REMBLOCKS'                => '... remove all template block entries',
    'D3TPLBLOCKS_REMBLOCKS_DESC'           => 'This function deletes all block entries of the selected module from the database. To re-add the entries, it is necessary to reactivate the corresponding module.',
    'D3TPLBLOCKS_REMBLOCKS_SUCC'           => 'The selected template block entries have been deleted.',
    'D3TPLBLOCKS_REFBLOCKS'                => '... update all templatebock entries',
    'D3TPLBLOCKS_REFBLOCKS_DESC'           => 'This function updates all block entries of the selected module in the database. Outdated entries are removed and new entries are added. <br> <br> Adapted position and active data are reconstructed, provided that the previous entries can be clearly assigned to the new entries. Otherwise, the default entries of the respective module are set for this.',
    'D3TPLBLOCKS_REFBLOCKS_SUCC'           => 'The selected template block entries have been updated.',
    'D3TPLBLOCKS_DEACTBLOCKS'              => '... disable all template block entries',
    'D3TPLBLOCKS_DEACTBLOCKS_DESC'         => 'This function deactivates all block entries of the selected module in the database. Note that reactivating the module will reactivate it. The changes do not become active until the TMP folder is emptied.',
    'D3TPLBLOCKS_DEACTBLOCKS_SUCC'         => 'The selected template block entries have been deactivated. Please empty the TMP folder.',
    'D3TPLBLOCKS_ACTBLOCKS'                => '... activate all template block entries',
    'D3TPLBLOCKS_ACTBLOCKS_DESC'           => 'This function activates all block entries of the selected module in the database. The changes do not become active until the TMP folder is emptied.',
    'D3TPLBLOCKS_ACTBLOCKS_SUCC'           => 'The selected template block entries have been activated. Please empty the TMP folder.',
    'D3TPLBLOCKS_CLEARDUPLICATES'          => 'Remove duplicates',
    'D3TPLBLOCKS_CLEARDUPLICATES_DESC'     => 'This function removes all duplicate block entries in the database. The changes do not become active until the TMP folder is emptied.',
    'D3TPLBLOCKS_CLEARDUPLICATES_SUCC'     => 'Multiple template block entries have been deleted. Please empty the TMP folder.',

    'D3_CFG_CLRTMP_ALL'                    => 'Clear <span style="font-weight: bold;">all</span>',
    'D3_CFG_CLRTMP_TPL'                    => 'Clear <span style="font-weight: bold;">template</span> cache',
    'D3_CFG_CLRTMP_DB'                     => 'Clear <span style="font-weight: bold;">datenbase</span> cache',
    'D3_CFG_CLRTMP_LANG'                   => 'Clear <span style="font-weight: bold;">language</span> cache',
    'D3_CFG_CLRTMP_MENU'                   => 'Clear <span style="font-weight: bold;">menu</span> cache',
    'D3_CFG_CLRTMP_CLASSPATH'              => 'Clear <span style="font-weight: bold;">classpath</span> cache',
    'D3_CFG_CLRTMP_STRUCTURE'              => 'Clear <span style="font-weight: bold;">structure</span> cache (categories, manufacturers, vendors)',
    'D3_CFG_CLRTMP_TAGCLOUD'               => 'Clear <span style="font-weight: bold;">tagcloud</span> cache',
    'D3_CFG_CLRTMP_SEO'                    => 'Clear <span style="font-weight: bold;">SEO</span> cache',
    'D3_CFG_CLRTMP_MODULE'                 => 'Clear <span style="font-weight: bold;">Module</span> cache',
    'D3_CFG_CLRTMP_VIEWS'                  => 'update <span style="font-weight: bold;">view</span> tables',
    'D3_CFG_CLRTMP_TPLBLOCKS'              => 'Remove <span style="font-weight: bold;">template blocks</span>',
    'D3_CFG_CLRTMP_TPLBLOCKS_REQUACT'      => 'requires module reactivation',
    'D3_CFG_CLRTMP_SUBMIT'                 => 'Clear TMP',
    'D3_CFG_CLRTMP_OR'                     => 'or',
    'D3_CFG_CLRTMP_MSG1'                   => 'TMP will cleared.',
    'D3_CFG_CLRTMP_MSG3'                   => 'Maintenance is performed.',
    'D3_CFG_CLRTMP_MSG2'                   => 'Please wait...',
    'D3_CFG_PLEASEWAIT'                    => 'Please wait...',

    'D3CLRTMP_LIB_TRANSL'                  => 'clear TMP',
    'D3CLRTMP_LIB_HELPLINK'                => 'Modul-Connector/TMP-leeren/',

    'D3_CFG_CLRTMP_STAT'                   => 'Statistic',
    'D3_CFG_CLRTMP_PATH'                   => 'Path:',
    'D3_CFG_CLRTMP_COUNT'                  => 'File count:',
    'D3_CFG_CLRTMP_SIZE'                   => 'Physical size:',
    'D3_CFG_CLRTMP_DELFOLDER'              => 'Foreign folders will deleted:',
    'D3_CFG_CLRTMP_CREATEHTA'              => '.htaccess will created:',
    'D3_CFG_CLRTMP_UPDATEVIEW'             => 'update view tables:',
    'D3_CFG_CLRTMP_CFG_TICKERTHRESHOLD'    => 'From this count of tmp files delete process will tickered:',
    'D3_CFG_CLRTMP_NO'                     => 'no',
    'D3_CFG_CLRTMP_YES'                    => 'yes',
    'D3_CFG_CLRTMP_SET_DESC'               => 'These settings can changed in admin panel in "Module Connector -> libraries".',
    'D3_CFG_CLRTMP_USETICKER'              => 'use ticker from',
    'D3_CFG_CLRTMP_USETICKERFILES'         => ' files',

    'D3_CFG_CLRTMP_DEV_LEGEND'             => 'Development Mode',
    'D3_CFG_CLRTMP_DEV_DESC'               => 'Developer mode prevents content from being dropped into the TMP directory. This allows you to quickly control template changes as well as language customizations. Please note, however, that this is an important performance optimization of the shop is disabled. Therefore, do not use developer mode without reason. <span style="font-weight: bold;"> Usage causes longer page load times. </span> <br> For this reason, Developer mode works only with <span style="font weight: bold;"> deactivated production mode </span> of the shop. <br> While using the developer mode, updates of the D3 module connector and its libraries can not be performed.',
    'D3_CFG_CLRTMP_DEV_BTNACT'             => 'activate development mode',
    'D3_CFG_CLRTMP_DEV_BTNDEACT'           => 'deactivate development mode',
    'D3_CFG_CLRTMP_DEV_DEACTPRODUCTIVE'    => 'For the developer mode, deactivate the productive mode of the shop.',

    'D3_CFG_CLRTMP_MODULELOGGING'          => 'Logging',
    'D3_CFG_CLRTMP_CFG_SHOWCLEARTMPOPTIONS'=> 'hide common clear tmp options',
    'D3_CFG_CLRTMP_CFG_SHOWCLEARTMPOPTIONS_DESC' => 'If your server constellation stores the shop\'s temporary files in a way that does not allow deletion from the extension, you can hide the default deletion features. If you have system commands to delete the files, you can configure and display them instead.',
    'D3_CFG_CLRTMP_CFG_SHOWNOHEADERFORM'   => '<span style="font-weight: bold;">don\'t</span> show clear tmp form in head area',
    'D3_CFG_CLRTMP_CFG_CREATE_NOHTACCESS'  => '<span style="font-weight: bold;">don\'t</span> create a .htaccess file',
    'D3_CFG_CLRTMP_CFG_REMOVEFOLDERS'      => '<span style="font-weight: bold;">don\'t</span> delete included foreign folders',
    'D3_CFG_CLRTMP_CFG_NOUPDATEVIEWS'      => '<span style="font-weight: bold;">don\'t</span> update view tables',
    'D3_CFG_CLRTMP_CFG_EXCLUDEREGEXP'      => 'RegExp pattern matches elements, which shouldn\'t deleted (without delimiter)',
    'D3_CFG_CLRTMP_CFG_EXCLUDEPATTERN_DESC'=> 'Specify a valid regular expression here that matches all files that are <b> NOT </b> to be deleted. The delimiter (%) is set by the script. Clear texts must be quoted appropriately. <br> Example: <ul> <li> <span style = "font-family: Courier, monospace;">. * </span> for all entries </li> <li> <span style="font-family: Courier, monospace;">. * \\. svn </span> for all files ending in .svn </li> </ul>',
    'D3_CFG_CLRTMP_HASNOEXCLUDEPATTERN'    => 'exclude pattern set',
    'D3_CFG_CLRTMP_CFG_USERACTION_DESC'    => 'With a custom deletion task, you can extend the TMP Empty tool with its own deletion tasks. These tasks are only shown if you have filled them.',
    'D3_CFG_CLRTMP_CFG_USERACTION_1'       => 'userdefined action 1:',
    'D3_CFG_CLRTMP_CFG_USERACTION_2'       => 'userdefined action 2:',
    'D3_CFG_CLRTMP_CFG_USERACTION_NAME'    => 'name',
    'D3_CFG_CLRTMP_CFG_USERACTION_NAME_DESC' => 'This title displays the deletion task in the clear TMP interface.',
    'D3_CFG_CLRTMP_CFG_USERACTION_PATTERN' => 'regexp pattern (without delimiter)',
    'D3_CFG_CLRTMP_CFG_USERACTION_PATTERN_DESC' => 'Enter a valid regular expression here, which matches all files that should be deleted. The delimiter (%) is set by the script. Clear texts must be quoted appropriately. <br> Example: <ul> <li> <span style="font-family: Courier, monospace;">. * </span> for all entries </li> <li> <span style="font-family: Courier, monospace;">. * \\ svn </span> for all files with the extension .svn </li> </ul> Deleted is only in the TMP folder of the shop.',
    'D3_CFG_CLRTMP_CFG_SYSTEMACTION_DESC'  => 'System commands allow you to extend the TMP Empty tool with its own maintenance tasks to be performed by the operating system. These tasks are only shown if you have filled them.',
    'D3_CFG_CLRTMP_CFG_SYSTEMACTION_1'     => 'system dependent maintenance task 1:',
    'D3_CFG_CLRTMP_CFG_SYSTEMACTION_2'     => 'system dependent maintenance task 2:',
    'D3_CFG_CLRTMP_CFG_SYSTEMACTION_NAME'  => 'name',
    'D3_CFG_CLRTMP_CFG_SYSTEMACTION_NAME_DESC' => 'This title displays the maintenance task in the clear TMP interface.',
    'D3_CFG_CLRTMP_CFG_SYSTEMACTION_CLRTMPREPLACE'  => 'command is a clear tmp replacement',
    'D3_CFG_CLRTMP_CFG_SYSTEMACTION_CLRTMPREPLACE_DESC' => 'Check this box if this command is a replacement for the TMP empty function. Other functions can automatically empty the temporary folder if necessary.',
    'D3_CFG_CLRTMP_CFG_SYSTEMACTION_ICON'  => 'icon',
    'D3_CFG_CLRTMP_CFG_SYSTEMACTION_ICON_DESC' => 'Within the buttons and options, we try to display icons for better distinction. For this we provide the symbol library of <a href="https://fontawesome.com/" target="fontawesome"> FontAwesome </a> (V 5.0.6). Specify a symbol class from it or your own CSS class. If you do not define a symbol, there is no display of the icon.',
    'D3_CFG_CLRTMP_CFG_SYSTEMACTION_COMMAND' => 'command',
    'D3_CFG_CLRTMP_CFG_SYSTEMACTION_COMMAND_DESC' => 'Enter a valid system command here, which starts your maintenance task. This call is sent to the operating system via PHP using exec (). Console outputs are stored as info status in the log. System commands must be sent via PHP. The purpose and success of the command is not controlled by our module. Please use this option with caution, as system commands may cause significant damage to the system.',
    'D3_CFG_CLRTMP_CFG_SAVE'               => 'save',

    'D3_CFG_CLRTMP_SUCCESS'                => 'The TMP folder was cleared.',
    'D3_CFG_CLRTMP_VIEWUPDATESUCCESS'      => 'View tables were updated.',
    'D3_CFG_CLRTMP_VIEWUPDATENOSUCCESS'    => 'View tables couldn\'t be updated.',
    'D3_CFG_CLRTMP_NOVALIDFSCLASS'         => 'Unable to clear the TMP folder - please update the install library!',

    'D3_CFG_CLRTMP_OTHER'                  => 'other maintenance tasks',
    'D3_CFG_CLRTMP_GENALLIMGS'             => 'remove all generated images',
    'D3_CFG_CLRTMP_GENIMGS'                => 'remove generated product images',
    'D3_CFG_CLRTMP_GENIMGS_SUCC'           => 'The generated product images have been deleted.',
    'D3_CFG_CLRTMP_GENIMGS_DESC'           => 'All generated product images will be deleted. The original product images remain valid for the new generation. If an article image is requested again, it will be regenerated from the source image. Please note that the original images must be available to the shop. Otherwise, the generation of the article images can not take place.',
	'D3_CFG_CLRTMP_GENCATIMGS'             => 'remove generated category images',
	'D3_CFG_CLRTMP_GENCATIMGS_SUCC'        => 'The generated category images have been deleted.',
	'D3_CFG_CLRTMP_GENCATIMGS_DESC'        => 'All generated category images will be deleted. The original category images remain valid for the new generation. If a category image is requested again, it will be regenerated from the source image. Please note that the original images must be available to the shop. Otherwise, the generation of the category images can not take place.',
	'D3_CFG_CLRTMP_GENMNFIMGS'             => 'remove generated manufacturer images',
	'D3_CFG_CLRTMP_GENMNFIMGS_SUCC'        => 'The generated manufacturer images have been deleted.',
	'D3_CFG_CLRTMP_GENMNFIMGS_DESC'        => 'All generated manufacturer images will be deleted. The original manufacturer images remain valid for the new generation. If a manufacturer image is requested again, it will be regenerated from the source image. Please note that the original images must be available to the shop. Otherwise, the generation of the manufacturer images can not take place.',
	'D3_CFG_CLRTMP_GENVNDIMGS'             => 'remove generated vendor images',
	'D3_CFG_CLRTMP_GENVNDIMGS_SUCC'        => 'The generated vendor images have been deleted.',
	'D3_CFG_CLRTMP_GENVNDIMGS_DESC'        => 'All generated vendor images will be deleted. The original vendor images remain valid for the new generation. If a vendor image is requested again, it will be regenerated from the source image. Please note that the original images must be available to the shop. Otherwise, the generation of the vendor images can not take place.',
	'D3_CFG_CLRTMP_GENWRPIMGS'             => 'remove generated wrapping images',
	'D3_CFG_CLRTMP_GENWRPIMGS_SUCC'        => 'The generated wrapping images have been deleted.',
	'D3_CFG_CLRTMP_GENWRPIMGS_DESC'        => 'All generated wrapping images will be deleted. The original wrapping images remain valid for the new generation. If a wrapping image is requested again, it will be regenerated from the source image. Please note that the original images must be available to the shop. Otherwise, the generation of the wrapping images can not take place.',
    'D3_CFG_CLRTMP_GENIMGS_WARN'           => 'Please make sure beforehand that all required images are original and can be regenerated. \n\nDo you want to clean up now?',

    'D3_CFG_CLRTMP_MISSING'                => 'add missing assignment table entries',
    'D3_CFG_CLRTMP_OXARTICLECONSIST'       => 'add missing oxartextends entries',
    'D3_CFG_CLRTMP_OXARTICLECONSIST_SUCC'  => '%1$d entries have been created.',
    'D3_CFG_CLRTMP_OXARTICLECONSIST_DESC'  => 'For each article entry in the database there should be a linked entry containing long texts of the article and further information. Especially if the data maintenance is carried out outside the shop, it may happen that the corresponding database entry is not created. This can lead to misconduct within the shop. This action creates the missing entries empty. Existing entries are not changed.',

    'D3_CFG_CLRTMP_ASSIGN'                 => 'Purge Mapping Tables from Orphan Entries:',
    'D3_CFG_CLRTMP_ASSIGN_DESC'            => 'If configurable entries (for example, articles or shipping types) are deleted, old assignment entries sometimes remain. Although these do not affect the query results, they slow down the query depending on the number of queries. This option cleans up unresolved mappings.',
    'D3_CFG_CLRTMP_ASSIGNACC2ART'          => 'Accessories mappings',
    'D3_CFG_CLRTMP_ASSIGNACC2ART_SUCC'     => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNACC2ART_DESC'     => 'table "oxaccessoire2article"',
    'D3_CFG_CLRTMP_ASSIGNACT2ART'          => 'Actions to articles mappings',
    'D3_CFG_CLRTMP_ASSIGNACT2ART_SUCC'     => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNACT2ART_DESC'     => 'table "oxactions2article"',
    'D3_CFG_CLRTMP_ASSIGNARTEXTENDS'          => 'Article long description',
    'D3_CFG_CLRTMP_ASSIGNARTEXTENDS_SUCC'     => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNARTEXTENDS_DESC'     => 'table "oxartextends"',
    'D3_CFG_CLRTMP_ASSIGNDEL2DELSET'       => 'Shipping mappings',
    'D3_CFG_CLRTMP_ASSIGNDEL2DELSET_SUCC'  => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNDEL2DELSET_DESC'  => 'table "oxdel2delset"',
    'D3_CFG_CLRTMP_ASSIGNCAT2ATTRIB'       => 'Attribute to category mappings',
    'D3_CFG_CLRTMP_ASSIGNCAT2ATTRIB_SUCC'  => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNCAT2ATTRIB_DESC'  => 'table "oxcategory2attribute"',
    'D3_CFG_CLRTMP_ASSIGNNEWSSUBSCRIBED'       => 'Newsletter registrations',
    'D3_CFG_CLRTMP_ASSIGNNEWSSUBSCRIBED_SUCC'  => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNNEWSSUBSCRIBED_DESC'  => 'table "oxnewssubscribed"',
    'D3_CFG_CLRTMP_ASSIGNOBJ2ACTION'          => 'Actions mappings',
    'D3_CFG_CLRTMP_ASSIGNOBJ2ACTION_SUCC'     => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNOBJ2ACTION_DESC'     => 'table "oxobject2action"',
    'D3_CFG_CLRTMP_ASSIGNOBJ2ART'          => 'Article to article mappings',
    'D3_CFG_CLRTMP_ASSIGNOBJ2ART_SUCC'     => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNOBJ2ART_DESC'     => 'table "oxobject2article"',
    'D3_CFG_CLRTMP_ASSIGNOBJ2ATTRIB'          => 'Attribute to article mappings',
    'D3_CFG_CLRTMP_ASSIGNOBJ2ATTRIB_SUCC'     => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNOBJ2ATTRIB_DESC'     => 'table "oxobject2attribute"',
    'D3_CFG_CLRTMP_ASSIGNOBJ2CAT'          => 'Article to category mappings',
    'D3_CFG_CLRTMP_ASSIGNOBJ2CAT_SUCC'     => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNOBJ2CAT_DESC'     => 'table "oxobject2category"',
    'D3_CFG_CLRTMP_ASSIGNOBJ2DEL'          => 'Shipping cost rules assignment',
    'D3_CFG_CLRTMP_ASSIGNOBJ2DEL_SUCC'     => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNOBJ2DEL_DESC'     => 'table "oxobject2delivery"',
    'D3_CFG_CLRTMP_ASSIGNOBJ2DISC'          => 'Various to discount mappings',
    'D3_CFG_CLRTMP_ASSIGNOBJ2DISC_SUCC'     => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNOBJ2DISC_DESC'     => 'table "oxobject2discount"',
    'D3_CFG_CLRTMP_ASSIGNOBJ2GROUP'          => 'Various to groups mappings',
    'D3_CFG_CLRTMP_ASSIGNOBJ2GROUP_SUCC'     => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNOBJ2GROUP_DESC'     => 'table "oxobject2group"',
    'D3_CFG_CLRTMP_ASSIGNOBJ2LIST'          => 'Article to recommendation mappings',
    'D3_CFG_CLRTMP_ASSIGNOBJ2LIST_SUCC'     => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNOBJ2LIST_DESC'     => 'table "oxobject2list"',
    'D3_CFG_CLRTMP_ASSIGNOBJ2PAYMENT'      => 'Payment mappings',
    'D3_CFG_CLRTMP_ASSIGNOBJ2PAYMENT_SUCC' => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNOBJ2PAYMENT_DESC' => 'table "oxobject2payment"',
    'D3_CFG_CLRTMP_ASSIGNOBJ2SELLIST'      => 'Article to selectlist mappings',
    'D3_CFG_CLRTMP_ASSIGNOBJ2SELLIST_SUCC' => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNOBJ2SELLIST_DESC' => 'table "oxobject2selectlist"',
    'D3_CFG_CLRTMP_ASSIGNPRICE2ART'      => 'Price to article mappings',
    'D3_CFG_CLRTMP_ASSIGNPRICE2ART_SUCC' => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNPRICE2ART_DESC' => 'Tabelle "oxprice2article"',
    'D3_CFG_CLRTMP_ASSIGNVARIANTWOPARENT'      => 'Delete variants without parent articles',
    'D3_CFG_CLRTMP_ASSIGNVARIANTWOPARENT_SUCC' => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_ASSIGNVARIANTWOPARENT_DESC' => 'Variants without parent articles can no longer be viewed in the shop. The articles including their long texts are deleted.',

    'D3_CFG_CLRTMP_VARIANTS'                => 'Clean up variant mappings',
    'D3_CFG_CLRTMP_VARIANTPARENTISVAR'      => 'Variant equal to parent article',
    'D3_CFG_CLRTMP_VARIANTPARENTISVAR_SUCC' => '%1$d entries have been changed.',
    'D3_CFG_CLRTMP_VARIANTPARENTISVAR_DESC' => 'In the case of incorrect variant imports, it may happen that a variant article has itself as a parent article. This can not be resolved in the shop. The item will not be displayed or even cause a loading error. This action resolves the wrong link and turns the article into a single article. You can then edit it again. If the article does not have its own title, it is named "unassigned article".',
    'D3_CFG_CLRTMP_VARIANTACTIVE'           => 'Disable variants of inactive parent items',
    'D3_CFG_CLRTMP_VARIANTACTIVE_SUCC'      => '%1$d entries have been changed.',
    'D3_CFG_CLRTMP_VARIANTACTIVE_DESC'      => 'For inactive parents, active variants do not make much sense. This option removes the active status for variant items that have an inactive parent item. This feature does not activate other items. Date-time information for the active detection is not taken into account.',

    'D3_CFG_CLRTMP_INACTIVE'                => 'remove inactive entries from mappings',
    'D3_CFG_CLRTMP_UNASSIGNINACTIVECOUNTRIES'   => 'inactive countries',
    'D3_CFG_CLRTMP_UNASSIGNINACTIVECOUNTRIES_SUCC'     => '%1$d entries have been deleted.',
    'D3_CFG_CLRTMP_UNASSIGNINACTIVECOUNTRIES_DESC'     => 'When setting up shipping costs are quickly assigned times "all countries". If these are not active, this only takes time unnecessarily for the selection. This option removes inactive countries from the map. If the countries are activated again, the assignment must be carried out again.',
    'D3_CFG_CLRTMP_DEACTIVATEEMPTYCATEGORIES'   => 'switch off empty categories',
    'D3_CFG_CLRTMP_DEACTIVATEEMPTYCATEGORIES_SUCC'     => '%1$d entries have been deactivated.',
    'D3_CFG_CLRTMP_DEACTIVATEEMPTYCATEGORIES_DESC'     => 'The shop offers the possibility to dynamically remove empty categories from the category tree. This is done again every time a page is called and consumes a lot of power. If the categories remain empty in the future, they can be permanently deactivated. The condition is that there are no active articles in it. The item inventory is not taken into account for the active check. Also not included are categories that include more subcategories.',

    'D3_CFG_CLRTMP_GENERAL_CLEARDB'        => 'Database entries may be deleted. Please create a backup of the database in advance. \n\nShould the cleanup be done now?',
    'D3_CFG_CLRTMP_GENERAL_CHANGEDB'       => 'Database entries may be changed. Please create a backup of the database in advance. \n\nShould the customization be done now?',
    'D3_CFG_MNT_CHECKALL'                  => 'check all items',
    'D3_CFG_MNT_SUBMIT'                    => 'operate action',
    'D3_CFG_MNT_SUCCESS'                   => 'Maintenance were operated.',

    'D3_CFG_CLRTMP_CLI_COMMON_RUNFROMCLI'  => 'This script has to be run from the command line',
    'D3_CFG_CLRTMP_CLI_COMMON_NOVALIDTYPE' => 'no valid type defined',
    'D3_CFG_CLRTMP_CLI_HELP'               => 'delete objects from temporary folder',
    'D3_CFG_CLRTMP_CLI_OPTION_VERSION'     => 'print version',
    'D3_CFG_CLRTMP_CLI_OPTION_QUIET'       => 'prevents output from being displayed',
    'D3_CFG_CLRTMP_CLI_OPTION_LANG'        => 'optional - language of the output messages, possible values are: "%1$s"',
    'D3_CFG_CLRTMP_CLI_OPTION_HELP'        => 'Display this help screen and exit immeadiately.',
    'D3_CFG_CLRTMP_CLI_OPTION_NOCOLORS'    => 'Do not use any colors in output. Useful when piping output to other tools or files.',
    'D3_CFG_CLRTMP_CLI_OPTION_LOGLEVELS'   => 'Minimum level of messages to display. Default is "info". Valid levels are: "%1$s".',
    'D3_CFG_CLRTMP_CLI_COMMAND'            => 'This tool accepts a command as first parameter as outlined below:',
    'D3_CFG_CLRTMP_CLI_COMMAND_RUN'        => 'Execution of the deletion order',
    'D3_CFG_CLRTMP_CLI_ARGUMENT_TYPE'      => 'Types of objects to be deleted, possible values are "%1$s"',
    'D3_CFG_CLRTMP_CLI_ARGUMENT_ENCLOSER'  => '", "',
    'D3_CFG_CLRTMP_CLI_FINISHED_SUCCFESSFULLY' => 'script successfully finished',
);
