<?php

/**
 * This Software is the property of Data Development and is protected
 * by copyright law - it is NOT Freeware.
 *
 * Any unauthorized use of this software without a valid license
 * is a violation of the license agreement and will be prosecuted by
 * civil and criminal law.
 *
 * http://www.shopmodule.com
 *
 * @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
 * @author    D3 Data Development - Daniel Seifert <support@shopmodule.com>
 * @link      http://www.oxidmodule.com
 */

$sLangName = "English";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
//Navigation
    'charset'                                          => 'UTF-8',
    'D3_INSTALL'                                       => 'Installation',

    'D3INSTALL_LIB_TRANSL'                             => 'Automatic Installation',

    'D3_INSTALL_SETUPSTEPS_INIT'                       => 'start installation',
    'D3_INSTALL_PROGRESS'                              => 'progess: ',

    'D3_INSTALL_STARTSETUP'                            => 'Create a backup of you database before the installation start, so that you can restore it in case of error. <br>File backups will create by the installation automaticly.',
    'D3_INSTALL_STARTSETUP1'                           => 'May you start the installation of "',
    'D3_INSTALL_STARTSETUP2'                           => '"?',
    'D3_INSTALL_SETUPCOUNT'                            => 'Update step #%s',
    'D3_INSTALL_SETUPCOUNT_DESC'                       => ' (%1$s)',
    'D3_INSTALL_SETUPSTEPS'                            => 'The following steps will executed:',
    'D3_INSTALL_SETUPSTEPS_GETARCHIVE'                 => 'module package will downloaded',
    'D3_INSTALL_SETUPSTEPS_LOADDESC'                   => 'module package will downloaded and extracted',
    'D3_INSTALL_SETUPSTEPS_EXTRACTARCHIVE'             => 'module package will extracted',
    'D3_INSTALL_SETUPSTEPS_SHOWDESCRIPTION'            => 'Description',
    'D3_INSTALL_SETUPSTEPS_COPYFILES'                  => 'files will copied (and backuped, if required) ',
    'D3_INSTALL_SETUPSTEPS_COPYFILES_DESC'             => 'All files inside the "copy_this" directory will copied into the shop, existing files will backuped.',
    'D3_INSTALL_SETUPSTEPS_COPYFILES_SOURCEPATH'       => 'source path',
    'D3_INSTALL_SETUPSTEPS_COPYFILES_DESTPATH'         => 'target path',
    'D3_INSTALL_SETUPSTEPS_ACTIVATEMODULE'             => 'activate module',
    'D3_INSTALL_SETUPSTEPS_ACTIVATEMODULE_DESC'        => 'This extension has to be registered in your shop. The module is thus <b>not</b> immediately active. In default case, our modules have a separate activation option, which then only activates their functions in the shop.',
    'D3_INSTALL_SETUPSTEPS_ACTIVATE'                   => '"%1$s" (%2$s)',
    'D3_INSTALL_SETUPSTEPS_MODSTEPS'                   => 'module items will written (module related)',
    'D3_INSTALL_SETUPSTEPS_DBITEMS'                    => 'database item will inserted (module related)',
    'D3_INSTALL_SETUPSTEPS_REGISTERMODULE'             => 'register module',
    'D3_INSTALL_SETUPSTEPS_REGISTERMODULE_DESC'        => 'The following module entries should be set. Existing extensions must be appended with the new entries.',
    'D3_INSTALL_SETUPSTEPS_REGISTERMODULE_NOITEMS'     => 'no new modul items available',
    'D3_INSTALL_SETUPSTEPS_SETDATA'                    => ' - Processing',
    'D3_INSTALL_SETUPSTEPS_FINISHED'                   => 'installation finished',
    'D3_INSTALL_SETUPSTEPS_FINISHED_DESC'              => 'The module installation was successfully completed.',
    'D3_INSTALL_SETUPSTEPS_FINISHED_DESC2'             => 'We wish you much success!',
    'D3_INSTALL_CLEANUP'                               => 'After installation, the TMP directory must be emptied. Should this be done now?',
    'D3_INSTALL_CLEANUPSTART'                          => 'clear TMP folder now',
    'D3_INSTALL_CLEANUPSUCCESS'                        => 'The TMP folder was cleared successfull.',
    'D3_INSTALL_CLEANUPNOTSUCCESS'                     => 'The TMP directory could not be (completely) emptied. Please do this yourself again.',
    'D3_INSTALL_PROTOKOLLURI'                          => 'The following installation log is also stored on your server: ',
    'D3_INSTALL_YES'                                   => 'automatic installation*',
    'D3_INSTALL_YESEXPERT'                             => 'user defined installation*',
    'D3_INSTALL_NO'                                    => 'cancel',
    'D3_INSTALL_SETUPDESC'                             => '* The express installation is completely automated. <br> With the "custom installation" you can also skip individual steps and perform them manually if necessary. This is recommended for strongly adapted shops.',
    'D3_INSTALL_SETUPSTEPS_ERROR'                      => 'error occured while installation',
    'D3_INSTALL_EXPMODEQUESTION'                       => 'Should the step be executed automatically or do you want to continue with the next point (the action should then be performed manually)?',
    'D3_INSTALL_EXPMODEEXECAUTO'                       => 'execute it automatic',
    'D3_INSTALL_EXPMODENXTSTEP'                        => 'continue with next step',
    'D3_INSTALL_NONEXISTINGSTEP'                       => 'The expected update function is unfortunately not available. If an update of the Module Connector is available, please install it beforehand. Try this installation again.',
    'D3_INSTALL_SETUPSTEPS_DESCCONTINUE'               => 'continue installation',
    'D3_INSTALL_DEPENDENCIES_POSSUPDATE'               => 'This library / module requires that another library in a particular version be installed before. It is likely that functions are mandatory. Install the following libraries before continuing this installation:',
    'D3_INSTALL_DEPENDENCIES_REQUNEWINSTALL'           => 'The available libraries can not be updated due to interdependencies. Please reinstall the "Initial Installation". You can download this package for free in our shop.',
    'D3_INSTALL_DEPENDENCIES_NOINSTALLPOSS'            => 'The installation requires libraries that are currently not available. Please contact us for further assistance.',
    'D3_INSTALL_DEPENDENCIES_UNDEFERROR'               => 'Unknown dependency: Please try to refresh the installation library first. Alternatively, please use the "Initial Installation Package" from our site oxidemodule.com for installation.',
    'D3_INSTALL_DEPENDENCIES_MINREV'                   => 'minimum in revision',
    'D3_INSTALL_DEPENDENCIES_MINVERSION'               => 'minimum in version',
    'D3_INSTALL_DEPENDENCIES_STARTINSTALL'             => '- start installation',
    'D3_INSTALL_SETUPSTEPS_IGNORE'                     => 'continue anyhow',
    'D3_INSTALL_ROLLBACK1'                             => 'During the installation an action could not be executed successfully. <br> <br> But that is not a problem. At what point the installation was aborted, please refer to the log entries below.',
    'D3_INSTALL_ROLLBACK2'                             => 'You have the choice:',
    'D3_INSTALL_ROLLBACK3'                             => 'You finish the installation yourself from this point, then please cancel here.',
    'D3_INSTALL_ROLLBACK5'                             => 'You can download the module here.',
    'D3_INSTALL_ROLLBACK4'                             => 'The previous installation is undone to start a new attempt (manually)',
    'D3_INSTALL_SETUPSTEPS_INITROLLBACK'               => 'Undo installation',
    'D3_INSTALL_ROLLBACKCANCEL'                        => 'cancel installation',
    'D3_INSTALL_SETUPSTEPS_ROLLBACK_COPYFILES'         => 'reset files',
    'D3_INSTALL_SETUPSTEPS_ROLLBACK_END'               => 'rollback finished',
    'D3_INSTALL_PROTOKOLL_SUCCESSFULL'                 => 'successfull',
    'D3_INSTALL_FINISH'                                => 'finish installation',
    'D3_INSTALL_PROTOKOLL_NOTSUCCESSFULL'              => 'error',
    'D3_INSTALL_FTPINFO_DISABLED'                      => 'If the installation is aborted due to a lack of rights, try the transfer via an FTP account. <br> Configure the settings in [D3 Modules] -> [System Settings] -> [Library Settings] -> [Installation Automation].',
    'D3_INSTALL_FTPINFO_ENABLED'                       => 'You are using FTP mode. This will take much more time for file operations. <br> Configure the settings in [D3 Modules] -> [System Settings] -> [Library Settings] -> [Installation Setup].',
    'D3_INSTALL_FTPINFO_CONFIG'                        => 'Enable FTP mode if library updates can not be performed due to lack of rights. Please note that file operations will take much longer. If possible, prefer the installation without FTP mode.',

    'D3_INSTALL_PROTOKOLLITEM_ACR'                     => 'rollback: system refreshed',
    'D3_INSTALL_PROTOKOLLITEM_ACT'                     => 'system refreshed',
    'D3_INSTALL_PROTOKOLLITEM_RMR'                     => 'rollback: module meta informations refreshed',
    'D3_INSTALL_PROTOKOLLITEM_RMM'                     => 'module meta informations refreshed',
    'D3_INSTALL_PROTOKOLLITEM_ARC'                     => 'error while downloading the archive',
    'D3_INSTALL_PROTOKOLLITEM_ARG'                     => 'archive downloaded',
    'D3_INSTALL_PROTOKOLLITEM_BFE'                     => 'unable to archive file',
    'D3_INSTALL_PROTOKOLLITEM_CDE'                     => 'unable to create directory',
    'D3_INSTALL_PROTOKOLLITEM_CFD'                     => 'unable to create directory',
    'D3_INSTALL_PROTOKOLLITEM_CFE'                     => 'no files to copy, is archive possible empty?',
    'D3_INSTALL_PROTOKOLLITEM_CFR'                     => 'files were overwritten, backup coies were created',
    'D3_INSTALL_PROTOKOLLITEM_CFG'                     => 'files were copied',
    'D3_INSTALL_PROTOKOLLITEM_CFM'                     => 'file permissions couldn\'t changed',
    'D3_INSTALL_PROTOKOLLITEM_CFN'                     => 'file couldn\'t copied',
    'D3_INSTALL_PROTOKOLLITEM_CLE'                     => 'TMP folder couldn\'t cleared, please clear it manually',
    'D3_INSTALL_PROTOKOLLITEM_CLT'                     => 'clear TMP folder',
    'D3_INSTALL_PROTOKOLLITEM_CNE'                     => 'Curl request isn\'t executable',
    'D3_INSTALL_PROTOKOLLITEM_DNC'                     => 'directory couldn\'t created: %s',
    'D3_INSTALL_PROTOKOLLITEM_DNC_E'                   => 'Could not create dir <b>%s</b>, please create it manually.<br>For further informations see <a href="http://faq.oxidmodule.de/">http://faq.oxidmodule.de/</a>',
    'D3_INSTALL_PROTOKOLLITEM_DND'                     => 'directory couldn\'t deleted: %s',
    'D3_INSTALL_PROTOKOLLITEM_DNM_E'                   => 'Unable to set write permissions for <b>%s</b>, please configure it manually.<br>For further informations see <a href="http://faq.oxidmodule.de/">http://faq.oxidmodule.de/</a>',
    'D3_INSTALL_PROTOKOLLITEM_DNO'                     => 'unable to read directory: %s',
    'D3_INSTALL_PROTOKOLLITEM_FCF'                     => 'unable to copy element: %s',
    'D3_INSTALL_PROTOKOLLITEM_FCG'                     => 'Group assignment can not be changed: %s',
    'D3_INSTALL_PROTOKOLLITEM_FCM'                     => 'Permissions can not be set: %s',
    'D3_INSTALL_PROTOKOLLITEM_FCO'                     => 'Owner can not be set: %s',
    'D3_INSTALL_PROTOKOLLITEM_FGG'                     => 'Group assignment can not be determined: %s',
    'D3_INSTALL_PROTOKOLLITEM_FGO'                     => 'Owner can not be determined: %s',
    'D3_INSTALL_PROTOKOLLITEM_FNC'                     => 'File can not be opened or created: %s',
    'D3_INSTALL_PROTOKOLLITEM_FND'                     => 'File can not be deleted: %s',
    'D3_INSTALL_PROTOKOLLITEM_FNP'                     => 'File access rights can not be read: %s',
    'D3_INSTALL_PROTOKOLLITEM_FNR'                     => 'File can not be read: %s',
    'D3_INSTALL_PROTOKOLLITEM_FNW'                     => 'File can not be written or no content exists.',
    'D3_INSTALL_PROTOKOLLITEM_FXS'                     => 'file doesn\'t exist: %s',
    'D3_INSTALL_PROTOKOLLITEM_RAG'                     => 'module archive saved',
    'D3_INSTALL_PROTOKOLLITEM_RFE'                     => 'Restore: no files found for restore',
    'D3_INSTALL_PROTOKOLLITEM_RFG'                     => 'Restore: Files have been copied back',
    'D3_INSTALL_PROTOKOLLITEM_RMG'                     => 'Modules registered',
    'D3_INSTALL_PROTOKOLLITEM_RMI'                     => 'Module registered',
    'D3_INSTALL_PROTOKOLLITEM_ROG'                     => 'oxutils module registered',
    'D3_INSTALL_PROTOKOLLITEM_RUG'                     => 'Restore: Restored oxutils module',
    'D3_INSTALL_PROTOKOLLITEM_RUE'                     => 'Restore: oxutils module could not be restored, backup exists',
    'D3_INSTALL_PROTOKOLLITEM_RRE'                     => 'Restore: Module entries could not be restored, backup exists',
    'D3_INSTALL_PROTOKOLLITEM_RRG'                     => 'Restore: Module entries restored',
    'D3_INSTALL_PROTOKOLLITEM_SNE'                     => 'System command can not be executed: %s',
    'D3_INSTALL_PROTOKOLLITEM_SQE'                     => 'Database entry set',
    'D3_INSTALL_PROTOKOLLITEM_SQL'                     => 'Database entries set',
    'D3_INSTALL_PROTOKOLLITEM_SQR'                     => 'Restore: Database not recoverable, please restore your own backup if necessary',
    'D3_INSTALL_PROTOKOLLITEM_SVG'                     => 'User input saved',
    'D3_INSTALL_PROTOKOLLITEM_XAN'                     => 'Unzip archive, no archive found',
    'D3_INSTALL_PROTOKOLLITEM_XAO'                     => 'archive extracted',
    'D3_INSTALL_PROTOKOLLITEM_XAS'                     => 'archive extracted',
    'D3_INSTALL_PROTOKOLLITEM_XNP'                     => 'unable to read XML',
    'D3_INSTALL_PROTOKOLLITEM_ZNF'                     => 'The size of the packed file can not be determined: %s',
    'D3_INSTALL_PROTOKOLLITEM_ZNN'                     => 'The name of the packed file can not be determined: %s',
    'D3_INSTALL_PROTOKOLLITEM_ZNO'                     => 'Can not open packed file %s: %s',
    'D3_INSTALL_PROTOKOLLITEM_ZNR'                     => 'packed file can not be read: %s',
    'D3_INSTALL_PROTOKOLL_SUCCESS'                     => 'installation will successfully finished',
    'D3_INSTALL_PROTOKOLL_ERROR'                       => 'There are errors during installation',
    'D3_INSTALL_PROTOKOLL_DETAILS'                     => '&nbsp;-&nbsp;click for details',

    'D3_INSTALL_CFG_FORCEFTP'                          => 'Use FTP connection to copy files',
    'D3_INSTALL_CFG_FORCEFTP_HELP'                     => 'The FTP connection to use must have sufficient permissions to delete and create files.',
    'D3_INSTALL_CFG_FTPSERVER'                         => 'FTP server name',
    'D3_INSTALL_CFG_FTPPORT'                           => 'FTP port (optional)',
    'D3_INSTALL_CFG_FTPPATH'                           => 'Path to the shoproot directory',
    'D3_INSTALL_CFG_FTPUSER'                           => 'FTP user name',
    'D3_INSTALL_CFG_FTPPASS'                           => 'FTP password (only if needed)',
    'D3_INSTALL_CFG_SAVE'                              => 'save',

    'D3_UPDATE_AVAILABLE_VERSION'                      => '<span style="margin: 10px;"><img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> <a href="%1$s" target="modupdate">New module version for "%2$s" (version %3$s) available.</a></span>',
    'D3_UPDATE_AVAILABLE_VERSION_NOLINK'               => '<span style="margin: 10px;"><img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> New module version for "%1$s" (version %2$s) available.</span>',
    'D3_UPDATE_EXPIREDMODULE'                          => '<span style="margin: 10px;"><img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> <a href="%1$s" target="_blank">The license of the module "%2$s" is expired. The functions are no longer available. Please contact us for an updated license.</a></span>',
    'D3_UPDATE_EXPIRESOONMODULE'                       => '<span style="margin: 10px;"><img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> <a href="%1$s" target="_blank" style="color: #F00000; font-weight: bold;">The license of the module "%2$s" expires in %3$s. The modul function will no longer be available. Please contact us for an updated license.</a></span>',
    'D3_UPDATE_REQUIRED_MODCFGUPDATE'                  => '<span style="margin: 10px;"><img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> <a href="%s" target="basefrm" style="color: #F00000; font-weight: bold;">Module connector requires an important installation. Click here to start the installation wizzard.</a></span>',

    'D3_CFG_MOD_UPDATE_TITLE'                          => 'D³ Module Installation Wizard',
    'D3_CFG_MOD_UPDATE_DESC'                           => 'Instead of the view you have chosen, you will see the module installation wizard here. This is shown because one or more of your D³ modules have to make some adjustments to the shop for their proper functioning.',
    'D3_CFG_MOD_UPDATE_SELECTDESC'                     => 'The installation wizard will be shown as one or more of your D³ modules need to make some adjustments to the shop for proper operation.',
    'D3_CFG_MOD_UPDATE_START'                          => 'Start',
    'D3_CFG_MOD_UPDATE_CHOOSESTEP'                     => 'Choose how you want to continue:',
    'D3_CFG_MOD_UPDATE_DEMOSHOP'                       => 'Since this shop runs in demo mode, not all options are selectable. Please contact the technical supervisor.',
    'D3_CFG_MOD_UPDATE_STEP_AUTOINSTALL'               => 'Automatic installation',
    'D3_CFG_MOD_UPDATE_STEP_AUTOINSTALL_DESC'          => 'The required installations are performed automatically with the default options. All actions are logged. <br> <b> This option is recommended for most shops. </b>',
    'D3_CFG_MOD_UPDATE_STEP_MANUALYINSTALL'            => 'Automatic installation with consultation',
    'D3_CFG_MOD_UPDATE_STEP_MANUALYINSTALL_DESC'       => 'The required installations are executed. Before each installation step you decide whether it should really be executed. <br> <b> This option is recommended for rather unusual server setups.</b>',
    'D3_CFG_MOD_UPDATE_STEP_CHECKLIST'                 => 'List for manual installation',
    'D3_CFG_MOD_UPDATE_STEP_CHECKLIST_DESC'            => 'The installation wizard will give you a list of the actions required. Changes to your shop are not made. <br> <b> Please note that the installations must be carried out to ensure proper functioning of the module connector and the modules based on it.</b>',
    'D3_CFG_MOD_UPDATE_STEP_SKIP'                      => 'Skip installation temporarily',
    'D3_CFG_MOD_UPDATE_STEP_SKIP_DESC'                 => 'You will be redirected to the originally selected page. However, the required installations are not performed. <br> <b> Please note that the installations must be performed to ensure the correct functioning of the module connector and the modules based on it. </b>',
    'D3_CFG_MOD_UPDATE_STEP_SKIP_RANGE1'               => '<br>At the earliest ',
    'D3_CFG_MOD_UPDATE_STEP_SKIP_RANGE2'               => ' you will be reminded again.',
    'D3_CFG_MOD_UPDATE_MULTIDESC'                      => 'The update must be carried out in several steps. Click on the button to complete the next steps.',
    'D3_CFG_MOD_UPDATE_MULTICONTINUE'                  => 'Continue update',
    'D3_CFG_MOD_UPDATE_STEPCONTINUE'                   => 'Perform installation step ...',
    'D3_CFG_MOD_UPDATE_SESSIONSKIP'                    => 'Skip in this session',
    'D3_CFG_MOD_UPDATE_SKIPEVER'                       => 'always skip',
    'D3_CFG_MOD_UPDATE_MULTIBACK'                      => 'back to action selection',
    'D3_CFG_MOD_UPDATE_JOB_SQL'                        => 'Execute this query in your shop database. When the installation is complete, empty the TMP folder and refresh the VIEW tables:',
    'D3_CFG_MOD_UPDATE_JOB_MODULE'                     => 'Activate these modules:',
    'D3_CFG_MOD_UPDATE_JOB_MSG'                        => 'Please note the following notes:',
    'D3_CFG_MOD_UPDATE_JOB_FILECONTENT'                => 'Customize the file "%s" or re-create it with the content:',
    'D3_CFG_MOD_UPDATE_ACTIVATEMODULE'                 => 'Modul "%s" (ID: "%s") in shop "%s (%s)"',
    'D3_CFG_MOD_UPDATE_JOB_BREAK'                      => 'The update has been paused because the further actions depend on the updates shown so far. First, run the previous updates and continue with this wizard. You will see the further update steps at this point.',
    'D3_CFG_MOD_UPDATE_JOB_ERROR'                      => 'Error during installation',
    'D3_CFG_MOD_UPDATE_JOB_ERROR_DESC'                 => 'The installation could not be carried out for the shown step. Please check this version manually and then continue the installation here.',
    'D3_CFG_MOD_UPDATE_JOB_ERRORMSG_DESC'              => 'The installation could not be carried out for the shown step. The following message was returned: <code>%s</code>. Please check this version manually and then continue the installation here.',
    'D3_CFG_MOD_UPDATE_WAIT'                           => 'Please wait...',
    'D3_CFG_MOD_UPDATE_NOUPDATE'                       => 'There are no (further) updates required for your shop.',
    'D3_CFG_MOD_UPDATE_NOUPDATEBACKLINK'               => 'Click <a href="%s">here</a>, to go back to the former page.',
    'D3_CFG_MOD_UPDATE_HASSKIPHASHES'                  => 'In your shop update actions are noted, which should be skipped. Should these update steps be reactivated?',
    'D3_CFG_MOD_UPDATE_DELSKIPHASHES'                  => 'reactivate skipped updates',
    'D3_CFG_MOD_UPDATE_MOREINFO'                       => '[ more ... ]',
    'D3_CFG_MOD_UPDATE_STEP_CHECK_SAVEASFILE'          => 'export as file',
    'D3_CFG_MOD_EXC_ALLLIBSDEACTIVATED'                => 'For reasons of system stability, all associated libraries were deactivated with this library. Please note that modules that require the D3 module connector will probably not work before the module connector has been completely re-enabled.',

    'D3_UPDATE_DISABLE_LOG_INSTALL_CLRTMP'             => 'Deactivate the following entries in "Extensions -> Modules" in the admin area. <ul><li>D3 Connector - Logging</li><li>D3 Connector - Installation wizard </li><li>D3 Connector - Clear TMP</li></ul>',
    'D3_UPDATE_DELETE_DIR'                             => 'Delete the directory "%s" and its contents from the server.',
    'D3_UPDATE_DELETE_DIRONCE'                         => 'Delete the directory "%s" from the server.',
    'D3_UPDATE_DELETE_FILEONCE'                        => 'The following file is obsolete and is no longer needed by the current version of the module. Please delete the file '. PHP_EOL. '"%s"'. PHP_EOL. 'from the server. If you execute this installation step, this file will be deleted automatically.',
    'D3_UPDATE_DELETE_CONFIGMODULEITEMS'               => 'There are registered extensions in the shop whose directory or files are not available. '. PHP_EOL. 'Please confirm the removal of these extensions. '. PHP_EOL. PHP_EOL. 'Alternatively, you can do this cleanup later in the admin area in '. PHP_EOL. 'Extensions -> Modules -> Perform installed shop modules.' , PHP_EOL. PHP_EOL. 'Affected extensions are: ',
    'D3_UPDATE_REGMLTABLECONFIG'                       => 'Basic shop settings (if available) are also read from the file "config.inc.php". <br> <br> Normally, this option is not used. Then simply continue this installation as normal. <br> <br> If you have entered the entry "%1$s" in the file, please change its contents there manually to the following value: <br> <br>%2$s <br> Unfortunately, the adjustments can be made not be done as part of the automatic installation.',
    'D3_UPDATE_MSG_UNREGISTERED_FILES'                 => 'Your module installation has the following unregistered files. To ensure the proper functioning of your module, you should check if these files can be removed. For security reasons, this installation step can not be performed automatically. Please delete the files manually and continue the installation here. Alternatively, skip this note with the "Skip" buttons shown below. <br> <br>%1$s <br> <br> If you have questions, contact the module author.',
    'D3_UPDATE_MSG_DISABLED_MODCFGMODULE'              => 'The D3 module connector has been temporarily deactivated by the shop software. Please activate this immediately, that this does not trigger any errors. '. PHP_EOL.PHP_EOL.'To reactivate the module:'. PHP_EOL .'- click on the "Run" -button on this page (if available) * or * '. PHP_EOL .'- call up in the admin area of your shop the menu item "Extensions -> Modules" - Execute the reactivation necessarily before the next installation steps. '. PHP_EOL.PHP_EOL.'In an enterprise edition with several clients, the reactivation is in every configured shop needed.',

    'D3_UPDATE_MSGADDTABLE'                            => 'add table "%1$s"',
);
