<?php //006f1
// This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Modul-Connector @version 6.0.1.0 PHPcust (03.08.2021) @author  Daniel Seifert support@shopmodule.com @copyright (C) 2021, D3 Data Development @see http://www.shopmodule.com
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cPokHx46qUDLsGILvOj2w9HaZr3B7vklkMuUuVLZH0KtTOjTM879TsAbf3P3fZwIVT1tCusyw
ghEXtLG3h+hjoO4r17/D0gSe1op6rFxEaBefNAB/ApUOEZrpcR0QcV6j9+7XzHMnOqasikmlp6o7
AS6YkSwc3BU5T4fGBpCsqjglmD2IGKEHyXqhUt08RqYNhbHfiAsPujfLA6zyCagyqXPqwtGCGCIr
2ZLxL7RXdZSg57E56xdB+S94DOeCBgYZlzkS+HROsVziBuQEjUKEZNISdlXgZ4MN+isdB5k1FyJG
ARvwKhY6/2b8l8DcOznOCF43nIKzH5Z4mJKOci5dR8qnRJ9E0RwOt+jDnnIi5ZKLwyVkXszGaiqx
lPfxJKDwVjiEPnCx8sH6ZVcQkNu1LeiVXYxOMqQQds1R86movV+BuoQszpfth11pKEx7vAwaiOgJ
A2Unk0FDW0E5oZSf2tokoGIExKiBIg4NFZDWVeCndDB1LogXoErt1NcsbxAjvRIsJ7YfmzCQke5t
M/3Wzyr3G/kBZQ03M4V4